/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthHomeRouteImport } from './routes/_auth/home'
import { Route as AuthFriendsRouteImport } from './routes/_auth/friends'
import { Route as InviteTokenIndexRouteImport } from './routes/invite/$token/index'
import { Route as FriendInviteTokenIndexRouteImport } from './routes/friend-invite/$token/index'
import { Route as InviteTokenVoteRouteImport } from './routes/invite/$token/vote'
import { Route as AuthPartyNewRouteImport } from './routes/_auth/party/new'
import { Route as AuthPartyPartyIdVoteRouteImport } from './routes/_auth/party/$partyId/vote'
import { Route as AuthPartyPartyIdResultRouteImport } from './routes/_auth/party/$partyId/result'
import { Route as AuthPartyPartyIdHubRouteImport } from './routes/_auth/party/$partyId/hub'
import { Route as AuthPartyPartyIdExploreRouteImport } from './routes/_auth/party/$partyId/explore'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthHomeRoute = AuthHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthFriendsRoute = AuthFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthRouteRoute,
} as any)
const InviteTokenIndexRoute = InviteTokenIndexRouteImport.update({
  id: '/invite/$token/',
  path: '/invite/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendInviteTokenIndexRoute = FriendInviteTokenIndexRouteImport.update({
  id: '/friend-invite/$token/',
  path: '/friend-invite/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenVoteRoute = InviteTokenVoteRouteImport.update({
  id: '/invite/$token/vote',
  path: '/invite/$token/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPartyNewRoute = AuthPartyNewRouteImport.update({
  id: '/party/new',
  path: '/party/new',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPartyPartyIdVoteRoute = AuthPartyPartyIdVoteRouteImport.update({
  id: '/party/$partyId/vote',
  path: '/party/$partyId/vote',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPartyPartyIdResultRoute = AuthPartyPartyIdResultRouteImport.update({
  id: '/party/$partyId/result',
  path: '/party/$partyId/result',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPartyPartyIdHubRoute = AuthPartyPartyIdHubRouteImport.update({
  id: '/party/$partyId/hub',
  path: '/party/$partyId/hub',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPartyPartyIdExploreRoute = AuthPartyPartyIdExploreRouteImport.update({
  id: '/party/$partyId/explore',
  path: '/party/$partyId/explore',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/friends': typeof AuthFriendsRoute
  '/home': typeof AuthHomeRoute
  '/profile': typeof AuthProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/party/new': typeof AuthPartyNewRoute
  '/invite/$token/vote': typeof InviteTokenVoteRoute
  '/friend-invite/$token/': typeof FriendInviteTokenIndexRoute
  '/invite/$token/': typeof InviteTokenIndexRoute
  '/party/$partyId/explore': typeof AuthPartyPartyIdExploreRoute
  '/party/$partyId/hub': typeof AuthPartyPartyIdHubRoute
  '/party/$partyId/result': typeof AuthPartyPartyIdResultRoute
  '/party/$partyId/vote': typeof AuthPartyPartyIdVoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/friends': typeof AuthFriendsRoute
  '/home': typeof AuthHomeRoute
  '/profile': typeof AuthProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/party/new': typeof AuthPartyNewRoute
  '/invite/$token/vote': typeof InviteTokenVoteRoute
  '/friend-invite/$token': typeof FriendInviteTokenIndexRoute
  '/invite/$token': typeof InviteTokenIndexRoute
  '/party/$partyId/explore': typeof AuthPartyPartyIdExploreRoute
  '/party/$partyId/hub': typeof AuthPartyPartyIdHubRoute
  '/party/$partyId/result': typeof AuthPartyPartyIdResultRoute
  '/party/$partyId/vote': typeof AuthPartyPartyIdVoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/_auth/friends': typeof AuthFriendsRoute
  '/_auth/home': typeof AuthHomeRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_auth/party/new': typeof AuthPartyNewRoute
  '/invite/$token/vote': typeof InviteTokenVoteRoute
  '/friend-invite/$token/': typeof FriendInviteTokenIndexRoute
  '/invite/$token/': typeof InviteTokenIndexRoute
  '/_auth/party/$partyId/explore': typeof AuthPartyPartyIdExploreRoute
  '/_auth/party/$partyId/hub': typeof AuthPartyPartyIdHubRoute
  '/_auth/party/$partyId/result': typeof AuthPartyPartyIdResultRoute
  '/_auth/party/$partyId/vote': typeof AuthPartyPartyIdVoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/welcome'
    | '/friends'
    | '/home'
    | '/profile'
    | '/auth/callback'
    | '/party/new'
    | '/invite/$token/vote'
    | '/friend-invite/$token/'
    | '/invite/$token/'
    | '/party/$partyId/explore'
    | '/party/$partyId/hub'
    | '/party/$partyId/result'
    | '/party/$partyId/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/welcome'
    | '/friends'
    | '/home'
    | '/profile'
    | '/auth/callback'
    | '/party/new'
    | '/invite/$token/vote'
    | '/friend-invite/$token'
    | '/invite/$token'
    | '/party/$partyId/explore'
    | '/party/$partyId/hub'
    | '/party/$partyId/result'
    | '/party/$partyId/vote'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/welcome'
    | '/_auth/friends'
    | '/_auth/home'
    | '/_auth/profile'
    | '/auth/callback'
    | '/_auth/party/new'
    | '/invite/$token/vote'
    | '/friend-invite/$token/'
    | '/invite/$token/'
    | '/_auth/party/$partyId/explore'
    | '/_auth/party/$partyId/hub'
    | '/_auth/party/$partyId/result'
    | '/_auth/party/$partyId/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteTokenVoteRoute: typeof InviteTokenVoteRoute
  FriendInviteTokenIndexRoute: typeof FriendInviteTokenIndexRoute
  InviteTokenIndexRoute: typeof InviteTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/home': {
      id: '/_auth/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/friends': {
      id: '/_auth/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthFriendsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/invite/$token/': {
      id: '/invite/$token/'
      path: '/invite/$token'
      fullPath: '/invite/$token/'
      preLoaderRoute: typeof InviteTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friend-invite/$token/': {
      id: '/friend-invite/$token/'
      path: '/friend-invite/$token'
      fullPath: '/friend-invite/$token/'
      preLoaderRoute: typeof FriendInviteTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token/vote': {
      id: '/invite/$token/vote'
      path: '/invite/$token/vote'
      fullPath: '/invite/$token/vote'
      preLoaderRoute: typeof InviteTokenVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/party/new': {
      id: '/_auth/party/new'
      path: '/party/new'
      fullPath: '/party/new'
      preLoaderRoute: typeof AuthPartyNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/party/$partyId/vote': {
      id: '/_auth/party/$partyId/vote'
      path: '/party/$partyId/vote'
      fullPath: '/party/$partyId/vote'
      preLoaderRoute: typeof AuthPartyPartyIdVoteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/party/$partyId/result': {
      id: '/_auth/party/$partyId/result'
      path: '/party/$partyId/result'
      fullPath: '/party/$partyId/result'
      preLoaderRoute: typeof AuthPartyPartyIdResultRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/party/$partyId/hub': {
      id: '/_auth/party/$partyId/hub'
      path: '/party/$partyId/hub'
      fullPath: '/party/$partyId/hub'
      preLoaderRoute: typeof AuthPartyPartyIdHubRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/party/$partyId/explore': {
      id: '/_auth/party/$partyId/explore'
      path: '/party/$partyId/explore'
      fullPath: '/party/$partyId/explore'
      preLoaderRoute: typeof AuthPartyPartyIdExploreRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthFriendsRoute: typeof AuthFriendsRoute
  AuthHomeRoute: typeof AuthHomeRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthPartyNewRoute: typeof AuthPartyNewRoute
  AuthPartyPartyIdExploreRoute: typeof AuthPartyPartyIdExploreRoute
  AuthPartyPartyIdHubRoute: typeof AuthPartyPartyIdHubRoute
  AuthPartyPartyIdResultRoute: typeof AuthPartyPartyIdResultRoute
  AuthPartyPartyIdVoteRoute: typeof AuthPartyPartyIdVoteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthFriendsRoute: AuthFriendsRoute,
  AuthHomeRoute: AuthHomeRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthPartyNewRoute: AuthPartyNewRoute,
  AuthPartyPartyIdExploreRoute: AuthPartyPartyIdExploreRoute,
  AuthPartyPartyIdHubRoute: AuthPartyPartyIdHubRoute,
  AuthPartyPartyIdResultRoute: AuthPartyPartyIdResultRoute,
  AuthPartyPartyIdVoteRoute: AuthPartyPartyIdVoteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteTokenVoteRoute: InviteTokenVoteRoute,
  FriendInviteTokenIndexRoute: FriendInviteTokenIndexRoute,
  InviteTokenIndexRoute: InviteTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
